<a href="https://colab.research.google.com/github/ghazalanaseem27-prog/code-practice/blob/main/numpy_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [5]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([84,  9, 74, 17, 62, 34, 21, 86, 11, 17, 68,  9, 46, 32, 93])

In [6]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[27, 48, 50, 96],
       [94, 50,  9, 25],
       [ 8, 91, 39, 25],
       [34,  9, 47,  8],
       [19, 86,  6,  9],
       [35, 51, 83, 55]])

In [7]:
np.sort(a)[::-1]

array([93, 86, 84, 74, 68, 62, 46, 34, 32, 21, 17, 17, 11,  9,  9])

In [8]:
np.sort(b,axis=0)

array([[ 8,  9,  6,  8],
       [19, 48,  9,  9],
       [27, 50, 39, 25],
       [34, 51, 47, 25],
       [35, 86, 50, 55],
       [94, 91, 83, 96]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [9]:
# code
np.append(a,200)

array([ 84,   9,  74,  17,  62,  34,  21,  86,  11,  17,  68,   9,  46,
        32,  93, 200])

In [10]:
b

array([[27, 48, 50, 96],
       [94, 50,  9, 25],
       [ 8, 91, 39, 25],
       [34,  9, 47,  8],
       [19, 86,  6,  9],
       [35, 51, 83, 55]])

In [11]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[2.70000000e+01, 4.80000000e+01, 5.00000000e+01, 9.60000000e+01,
        4.53383943e-01],
       [9.40000000e+01, 5.00000000e+01, 9.00000000e+00, 2.50000000e+01,
        1.14555872e-01],
       [8.00000000e+00, 9.10000000e+01, 3.90000000e+01, 2.50000000e+01,
        1.81591392e-01],
       [3.40000000e+01, 9.00000000e+00, 4.70000000e+01, 8.00000000e+00,
        3.34256209e-01],
       [1.90000000e+01, 8.60000000e+01, 6.00000000e+00, 9.00000000e+00,
        4.75466037e-01],
       [3.50000000e+01, 5.10000000e+01, 8.30000000e+01, 5.50000000e+01,
        6.25274341e-03]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [12]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [13]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [15]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [16]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [17]:
# code
a.shape

(15,)

In [18]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [19]:
np.expand_dims(a,axis=1)

array([[84],
       [ 9],
       [74],
       [17],
       [62],
       [34],
       [21],
       [86],
       [11],
       [17],
       [68],
       [ 9],
       [46],
       [32],
       [93]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [20]:
a

array([84,  9, 74, 17, 62, 34, 21, 86, 11, 17, 68,  9, 46, 32, 93])

In [21]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  2,  4,  7, 10, 14]),)

In [22]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 0,  9,  0, 17,  0, 34, 21,  0, 11, 17,  0,  9, 46, 32,  0])

In [23]:
np.where(a%2 == 0,0,a)

array([ 0,  9,  0, 17,  0,  0, 21,  0, 11, 17,  0,  9,  0,  0, 93])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [24]:
# code
a

array([84,  9, 74, 17, 62, 34, 21, 86, 11, 17, 68,  9, 46, 32, 93])

In [25]:
np.argmax(a)

np.int64(14)

In [26]:
b

array([[27, 48, 50, 96],
       [94, 50,  9, 25],
       [ 8, 91, 39, 25],
       [34,  9, 47,  8],
       [19, 86,  6,  9],
       [35, 51, 83, 55]])

In [27]:
np.argmax(b,axis=0)

array([1, 2, 5, 0])

In [28]:
np.argmax(b,axis=1)

array([3, 0, 1, 2, 1, 2])

In [29]:
# np.argmin
np.argmin(a)

np.int64(1)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [30]:
a

array([84,  9, 74, 17, 62, 34, 21, 86, 11, 17, 68,  9, 46, 32, 93])

In [31]:
np.cumsum(a)

array([ 84,  93, 167, 184, 246, 280, 301, 387, 398, 415, 483, 492, 538,
       570, 663])

In [32]:
b

array([[27, 48, 50, 96],
       [94, 50,  9, 25],
       [ 8, 91, 39, 25],
       [34,  9, 47,  8],
       [19, 86,  6,  9],
       [35, 51, 83, 55]])

In [33]:
np.cumsum(b,axis=1)

array([[ 27,  75, 125, 221],
       [ 94, 144, 153, 178],
       [  8,  99, 138, 163],
       [ 34,  43,  90,  98],
       [ 19, 105, 111, 120],
       [ 35,  86, 169, 224]])

In [66]:
np.cumsum(b)

array([  27,   75,  125,  221,  315,  365,  374,  399,  407,  498,  537,
        562,  596,  605,  652,  660,  679,  765,  771,  780,  815,  866,
        949, 1004])

In [67]:
# np.cumprod
np.cumprod(a)

array([                 110,                58300,              4314200,
                   73341400,           4547166800,         154603671200,
              3246677095200,      279214230187200,     3071356532059200,
          52213061045006400,  3550488151060435200, -4939094787875186432,
       -5837431357743956480, -2330362710711091200,  4637196788383137792])

In [36]:
a

array([84,  9, 74, 17, 62, 34, 21, 86, 11, 17, 68,  9, 46, 32, 93])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [37]:
a

array([84,  9, 74, 17, 62, 34, 21, 86, 11, 17, 68,  9, 46, 32, 93])

In [38]:
np.percentile(a,50)

np.float64(34.0)

In [39]:
np.median(a)

np.float64(34.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [40]:
# code
a

array([84,  9, 74, 17, 62, 34, 21, 86, 11, 17, 68,  9, 46, 32, 93])

In [41]:
np.histogram(a,bins=[0,50,100])

(array([9, 6]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [42]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [43]:
# code
a


array([84,  9, 74, 17, 62, 34, 21, 86, 11, 17, 68,  9, 46, 32, 93])

In [44]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([], dtype=int64)

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [45]:
# code
a

array([84,  9, 74, 17, 62, 34, 21, 86, 11, 17, 68,  9, 46, 32, 93])

In [46]:
np.flip(a)

array([93, 32, 46,  9, 68, 17, 11, 86, 21, 34, 62, 17, 74,  9, 84])

In [47]:
b

array([[27, 48, 50, 96],
       [94, 50,  9, 25],
       [ 8, 91, 39, 25],
       [34,  9, 47,  8],
       [19, 86,  6,  9],
       [35, 51, 83, 55]])

In [48]:
np.flip(b,axis=1)

array([[96, 50, 48, 27],
       [25,  9, 50, 94],
       [25, 39, 91,  8],
       [ 8, 47,  9, 34],
       [ 9,  6, 86, 19],
       [55, 83, 51, 35]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [49]:
# code
a

array([84,  9, 74, 17, 62, 34, 21, 86, 11, 17, 68,  9, 46, 32, 93])

In [50]:
np.put(a,[0,1],[110,530])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [51]:
# code
a

array([110, 530,  74,  17,  62,  34,  21,  86,  11,  17,  68,   9,  46,
        32,  93])

In [52]:
np.delete(a,[0,2,4])

array([530,  17,  34,  21,  86,  11,  17,  68,   9,  46,  32,  93])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [53]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [54]:
np.intersect1d(m,n)

array([3, 4, 5])

In [55]:
np.setdiff1d(n,m)

array([6, 7])

In [56]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [57]:
m[np.in1d(m,1)]

/tmp/ipykernel_389/524887286.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,1)]


array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [68]:
# code
a

array([110, 530,  74,  17,  62,  34,  21,  86,  11,  17,  68,   9,  46,
        32,  93])

In [59]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 74, 25, 62, 34, 25, 75, 25, 25, 68, 25, 46, 32, 75])

In [60]:
# 17. np.swapaxes

In [61]:
# 18. np.uniform

In [62]:
# 19. np.count_nonzero

In [63]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [64]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [65]:

# 25. np.allclose and equals